image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

stages:
  - build
  - test
  - publish

wheels:
  stage: build
  script: python setup.py bdist_wheel
  artifacts:
    paths:
    - dist/

pytest:
  stage: test
  script:
  - pytest

publish:
  stage: publish
  script:
    - pip install --upgrade twine
    - twine upload -u __token__ -p $PYPI_TOKEN dist/*
  only:
    - master

#publish_test:
#  stage: publish
#  script:
#    - pip install --upgrade twine
#    - twine upload -u __token__ -p $TESTPYPI_TOKEN --repository testpypi dist/*
